apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hybrid-rag.fullname" . }}
  labels:
    {{- include "hybrid-rag.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "hybrid-rag.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "hybrid-rag.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              valueFrom:
                {{- toYaml .valueFrom | nindent 16 }}
            {{- end }}
          resources: {}